import { LayoutTemplate, HeaderProps } from '@/types/layout';

export const headerTemplates: LayoutTemplate<HeaderProps>[] = [
  {
    id: 'header-classic',
    name: 'Classic',
    thumbnail: '/placeholder.svg',
    defaults: {
      layout: 'logo-nav-actions',
      logo: { type: 'text', text: 'YourBrand' },
      nav: [
        { label: 'Home', href: '/' },
        { label: 'Explore', href: '/discover' },
        { label: 'Store', href: '/products' },
        { label: 'Contact', href: '/contact' },
      ],
      showProfile: true,
      sticky: false,
      height: 64,
      background: 'hsl(var(--background))',
      textColor: 'hsl(var(--foreground))',
      collapseToBurger: true,
    },
    styles: {
      '--hdr-height': 64,
      '--hdr-shadow': 'var(--shadow-card)',
      '--hdr-border': 'none',
    },
    apply: (cur) => ({
      ...cur,
      layout: 'logo-nav-actions',
      nav: cur.nav && cur.nav.length > 0 ? cur.nav : [
        { label: 'Home', href: '/' },
        { label: 'Explore', href: '/discover' },
        { label: 'Store', href: '/products' },
        { label: 'Contact', href: '/contact' },
      ],
      sticky: false,
      height: 64,
    }),
  },
  {
    id: 'header-centered',
    name: 'Centered Logo',
    thumbnail: '/placeholder.svg',
    defaults: {
      layout: 'nav-logo-actions',
      logo: { type: 'text', text: 'BRAND' },
      nav: [
        { label: 'Shop', href: '/shop' },
        { label: 'About', href: '/about' },
      ],
      showProfile: true,
      sticky: false,
      height: 72,
      background: 'hsl(var(--background))',
      textColor: 'hsl(var(--foreground))',
      collapseToBurger: true,
    },
    styles: {
      '--hdr-height': 72,
      '--hdr-border': '1px solid hsl(var(--border))',
    },
    apply: (cur) => ({
      ...cur,
      layout: 'nav-logo-actions',
      height: 72,
      sticky: false,
    }),
  },
  {
    id: 'header-minimal',
    name: 'Minimal',
    thumbnail: '/placeholder.svg',
    defaults: {
      layout: 'logo-actions',
      logo: { type: 'text', text: 'Brand' },
      nav: [],
      showProfile: true,
      sticky: false,
      height: 56,
      background: 'hsl(var(--background))',
      textColor: 'hsl(var(--foreground))',
      collapseToBurger: false,
    },
    styles: {
      '--hdr-height': 56,
      '--hdr-shadow': 'none',
    },
    apply: (cur) => ({
      ...cur,
      layout: 'logo-actions',
      nav: [],
      sticky: false,
      height: 56,
    }),
  },
  {
    id: 'header-sticky-gradient',
    name: 'Sticky Gradient',
    thumbnail: '/placeholder.svg',
    defaults: {
      layout: 'logo-nav-actions',
      logo: { type: 'text', text: 'Brand' },
      nav: [
        { label: 'Home', href: '/' },
        { label: 'Features', href: '/features' },
        { label: 'Pricing', href: '/pricing' },
      ],
      showProfile: true,
      sticky: true,
      stickyBehavior: 'shrink-on-scroll',
      height: 72,
      background: 'linear-gradient(135deg, hsl(var(--primary)), hsl(var(--secondary)))',
      textColor: 'hsl(var(--primary-foreground))',
      collapseToBurger: true,
    },
    styles: {
      '--hdr-height': 72,
      '--hdr-shadow': 'var(--shadow-glow)',
    },
    apply: (cur) => ({
      ...cur,
      layout: 'logo-nav-actions',
      sticky: true,
      stickyBehavior: 'shrink-on-scroll',
      height: 72,
      background: 'linear-gradient(135deg, hsl(var(--primary)), hsl(var(--secondary)))',
    }),
  },
  {
    id: 'header-search',
    name: 'Search Focus',
    thumbnail: '/placeholder.svg',
    defaults: {
      layout: 'logo-search-actions',
      logo: { type: 'text', text: 'Brand' },
      nav: [
        { label: 'Shop', href: '/shop' },
      ],
      showProfile: true,
      showSearch: true,
      sticky: false,
      height: 64,
      background: 'hsl(var(--background))',
      textColor: 'hsl(var(--foreground))',
      collapseToBurger: false,
    },
    styles: {
      '--hdr-height': 64,
    },
    apply: (cur) => ({
      ...cur,
      layout: 'logo-search-actions',
      showSearch: true,
      height: 64,
    }),
  },
  {
    id: 'header-burger',
    name: 'Mobile-first Burger',
    thumbnail: '/placeholder.svg',
    defaults: {
      layout: 'logo-burger',
      logo: { type: 'text', text: 'Brand' },
      nav: [
        { label: 'Home', href: '/' },
        { label: 'Products', href: '/products' },
        { label: 'About', href: '/about' },
        { label: 'Contact', href: '/contact' },
      ],
      showProfile: false,
      sticky: false,
      height: 60,
      background: 'hsl(var(--background))',
      textColor: 'hsl(var(--foreground))',
      collapseToBurger: true,
    },
    styles: {
      '--hdr-height': 60,
    },
    apply: (cur) => ({
      ...cur,
      layout: 'logo-burger',
      collapseToBurger: true,
      height: 60,
    }),
  },
];
