// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbathtesoijkchzqsxwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiYXRodGVzb2lqa2NoenFzeHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyNjQwOTUsImV4cCI6MjA3NDg0MDA5NX0.PTLWCI8rwqdwX4Cmd1N_AI8KYFiuTzU422GIDngXjME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});